name: Build and Test the app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install NPM dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Display SoftUni username
        run: echo "name"
